name: Build Docker Container
on:
  push:
    branches:
      - main
      - master 
jobs:
  docker:
    runs-on: 176.97.218.73
    steps:
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
