name: Build Docker Container
on:
  push:
    branches:
      - main
      - master 
jobs:
  run-test:
    runs-on: srv4795496900
    steps:
    - uses: actions/checkout@v2
      name: Pull Source Code
    - name: Build Backend stage image
      run: |
         docker build -t registry.dosma.ir/stage/backend:${{github.sha}} .
      shell: bash
