name: Build Docker Container
on:
  push:
    branches:
      - staging
jobs:
  run-test:
    runs-on: [self-hosted , Linux, X64, stage]
    steps:
    - uses: actions/checkout@v2
      name: Pull Source Code
    - name: Build Backend stage image
      run: |
         docker build -t registry.**.*/backend:${{github.sha}} .
      shell: bash
    - name: Change version
      run: |
         sed -i   's/image:.*/image: registry.***.*\/backend:${{github.sha}}/' /opt/backend/docker-compose.yml 
      shell: bash
    - name: compose up
      run: |
        docker compose -f /opt/backend/docker-compose.yml up -d
      shell: bash
