name: Build Docker Container
on:
  push:
    branches:
      - main
      - master 
jobs:
  docker:
    runs-on: stage
    steps:
    - uses: actions/checkout@v2
    - name: Build Backend stage image
      run: |
         docker build -t registry.dosma.ir/stage/backend:${{github.sha} .
      shell: bash
